## Basic Configuration
baseurl = "https://johnmcdonnell.net"
languageCode = "en-ie"
title = "Title"
theme = "hyde-hyde"

[params]
    author = "John McDonnell"
    title = "Title"
    # description = "..."
    dateformat = "2/01/2006"

    # sidebar, copyright & license
    copyright = "John McDonnell"
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

[params.social]
    github = "mcdonnell-john"
    linkedin = "johnmcdonnell1"
    gravatar = "mcdonnell.john@gmail.com"
